version: "3"

tasks:
  compose:
    desc: "Launch docker-compose (if not launched)"
    cmds:
      - docker compose -f deploy/docker-compose.local.yaml up -d
    status:
      - test -n "$(docker compose -f deploy/docker-compose.local.yaml ps -q)"

  proto:
    cmds:
      - protoc --go_out=. --go-grpc_out=. core/proto/converter.proto

  compose-down:
    desc: "Stop and remove docker-compose.local.yaml"
    cmds:
      - docker compose -f deploy/docker-compose.local.yaml down -v
    status:
      - test -z "$(docker compose -f deploy/docker-compose.local.yaml ps -q)"

  converter:
    deps:
      - compose
    cmds:
      - mkdir -p bin
      - go build -o bin/converter ./converter/cmd/converter
      - ./bin/converter

  distributor:
    deps:
      - compose
    cmds:
      - mkdir -p bin
      - go build -o bin/distributor ./distributor/cmd/distributor
      - ./bin/distributor

  api:
    desc: "Build and run api/cmd/api/main.go"
    deps:
      - compose
    cmds:
      - mkdir -p bin
      - go build -o bin/api ./api/cmd/api
      - ./bin/api

  client:
    desc: "Build and run api/cmd/client/client.go"
    deps:
      - compose
    dir: .
    cmds:
      - mkdir -p bin
      - go build -o bin/client ./client
      - ./bin/client
