version: "3"

tasks:
  compose-local:
    desc: "Launch docker-compose (if not launched)"
    cmds:
      - docker compose -f deploy/docker-compose.local.yaml up -d
    status:
      - test -n "$(docker compose -f deploy/docker-compose.local.yaml ps -q)"

  proto:
    dir: core
    cmds:
      - protoc --go_out=. --go-grpc_out=. proto/converter.proto

  compose-local-down:
    desc: "Stop and remove docker-compose.local.yaml"
    cmds:
      - docker compose -f deploy/docker-compose.local.yaml down -v
    status:
      - test -z "$(docker compose -f deploy/docker-compose.local.yaml ps -a -q)"

  converter:
    deps:
      - compose
    dir: converter
    cmds:
      - mkdir -p ../bin
      - go build -buildvcs=false -o ../bin/converter ./cmd/converter
      - ../bin/converter

  distributor:
    deps:
      - compose
    dir: distributor
    cmds:
      - mkdir -p ../bin
      - go build -buildvcs=false -o ../bin/distributor ./cmd/distributor
      - ../bin/distributor

  ingress:
    desc: "Build and run ingress/cmd/ingress/main.go"
    deps:
      - compose
    dir: ingress
    cmds:
      - mkdir -p ../bin
      - go build -buildvcs=false -o ../bin/ingress ./cmd/ingress
      - ../bin/ingress

  client:
    desc: "Build and run client/client.go"
    dir: client
    cmds:
      - mkdir -p ../bin
      - go build -buildvcs=false -o ../bin/client .
      - ../bin/client

  # ================= DEV COMPOSE =================

  compose-dev:
    desc: "Launch docker-compose.dev.yaml (if not launched)"
    cmds:
      - docker compose -f deploy/docker-compose.dev.yaml up
    status:
      - test -n "$(docker compose -f deploy/docker-compose.dev.yaml ps -q)"

  compose-dev-build:
    desc: "Rebuild images and launch dev stack (ingress, distributor, converter)"
    cmds:
      - docker compose -f deploy/docker-compose.dev.yaml up --build

  rebuild-dev-services:
    desc: "Rebuild Docker images for ingress, distributor, converter (dev)"
    cmds:
      - docker compose -f deploy/docker-compose.dev.yaml build ingress distributor converter

  compose-dev-down:
    desc: "Stop dev stack and remove containers, volumes and images of dev services"
    cmds:
      - docker compose -f deploy/docker-compose.dev.yaml down -v --rmi local
    status:
      - test -z "$(docker compose -f deploy/docker-compose.dev.yaml ps -a -q)"
