FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY ./core ./core

COPY ./converter/go.mod ./converter/go.sum ./converter/

WORKDIR /app/converter
RUN go mod download

COPY ./converter .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o converter-service ./cmd/converter

FROM alpine:3.22
WORKDIR /app

COPY --from=builder /app/converter/converter-service /usr/local/bin/converter-service
COPY --from=builder /app/converter/configs /configs

ENTRYPOINT ["/usr/local/bin/converter-service"]
