FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o converter-service ./cmd/converter

FROM alpine:3.19
WORKDIR /app

RUN mkdir -p /app/data

COPY --from=builder /app/converter /usr/local/bin/converter

EXPOSE 50051

ENTRYPOINT ["/usr/local/bin/converter", "-addr=:50051", "-base-dir=/app/data"]
